name: CheckStyle_Comments
on: pull_request

jobs:
  phpmd_checkstyle:
    name: CheckStyle Comments

    runs-on: ubuntu-latest
    env:
      php: "7.4"
      extensions: mbstring, ctype, curl, gd, apcu, memcached

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php }}
          extensions: ${{ env.extensions }}
          coverage: none
          tools: composer:v2, cs2pr

      - name: "Install locked dependencies from composer.lock"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: Run PHPMD
        run: src/bin/phpmd src/main/php/PHPMD/Renderer checkstyle cleancode | cs2pr